#!/bin/bash

NATIVE_IMAGE="$GRAALVM_HOME/bin/native-image"

if [ -z "$NATIVE_IMAGE" ]; then
    echo 'Please set $NATIVE_IMAGE'
    exit 1
fi

clojure -e "(compile 'reconsierge.main)"

# -jar target/reconsierge.jar

$NATIVE_IMAGE \
    -cp $(clojure -Spath):classes \
    -H:Name=reconsierge \
    -H:+ReportExceptionStackTraces \
    --initialize-at-build-time  \
    --verbose \
    --no-fallback \
    --no-server \
    --language:js \
    "-J-Xmx3g" \
    reconsierge.main
